/**
 * @api {none} / Model Structure
 * @apiVersion 0.0.1
 * @apiName Model
 * @apiGroup Department
 *
 * @apiDeprecated This is only used to define the model.
 *
 * @apiSuccess (Model Autogenerated) {String} _id MongoID this is autogenerated depending on the HTTP method
 * @apiSuccess (Model Autogenerated) {String} updated_at Indicated when the document has been updated
 * @apiSuccess (Model Autogenerated) {String} created_at Indicated when the document has been created
 * @apiSuccess (Model) {String} name
 * @apiSuccess (Model) {String} [code]
 * @apiSuccess (Model) {String} [tel]
 * @apiSuccess (Model) {Object} [location_coordinates]
 * @apiSuccess (Model) {Number[]}   .coordinates
 * @apiSuccess (Model) {Object} [address]
 * @apiSuccess (Model) {String}     .street
 * @apiSuccess (Model) {String}     .house_number
 * @apiSuccess (Model) {String}     .city
 * @apiSuccess (Model) {String}     .zip_code
 * @apiSuccess (Model) {Object} [region]
 * @apiSuccess (Model) {String}     [.name]
 */

/**
 * @api {none} / Model Structure
 * @apiVersion 0.0.2
 * @apiName Model
 * @apiGroup Department
 *
 * @apiDeprecated This is only used to define the model.
 *
 * @apiSuccess (Model Autogenerated) {String} _id MongoID this is autogenerated depending on the HTTP method
 * @apiSuccess (Model Autogenerated) {String} updated_at Indicated when the document has been updated
 * @apiSuccess (Model Autogenerated) {String} created_at Indicated when the document has been created
 * @apiSuccess (Model) {String} name
 * @apiSuccess (Model) {String} [code]
 * @apiSuccess (Model) {String} [tel]
 * @apiSuccess (Model) {Object} [location_coordinates]
 * @apiSuccess (Model) {Number[]}   .coordinates
 * @apiSuccess (Model) {Object} [address]
 * @apiSuccess (Model) {String}     .street
 * @apiSuccess (Model) {String}     .house_number
 * @apiSuccess (Model) {String}     .city
 * @apiSuccess (Model) {String}     .zip_code
 * @apiSuccess (Model) {Object} [region]
 * @apiSuccess (Model) {String}     [.name]
 */

/**
 * @api {get} /departments Get Departments
 * @apiVersion 0.0.1
 * @apiName Get
 * @apiGroup Department
 *
 * @apiuse JwtHeader
 *
 * @apiUse Response
 * @apiSuccess {Department[]} data Array of <a href="#api-Department-Model">Department</a>s
 *
 */

/**
 * @api {get} /departments/:id Get Department
 * @apiVersion 0.0.1
 * @apiName GetOne
 * @apiGroup Department
 *
 * @apiuse JwtHeader
 * 
 * @apiParam (Query) {String} id MongoID
 *
 * @apiUse Response
 * @apiSuccess {Department} data of <a href="#api-Department-Model">Department</a> for the specified id
 *
 */

/**
 * @api {post} /departments Post Department
 * @apiVersion 0.0.1
 * @apiName Post
 * @apiGroup Department
 *
 * @apiuse JwtHeader
 *
 * @apiUse Response
 * @apiSuccess {Department} data <a href="#api-Department-Model">Department</a> that has been posted
 *
 */

/**
 * @api {delete} /departments/:id Delete Department
 * @apiVersion 0.0.1
 * @apiName Delete
 * @apiGroup Department
 *
 * @apiuse JwtHeader
 *
 * @apiParam (Query) {String} id MongoID
 *
 * @apiUse Response
 * @apiSuccess {Department} data <a href="#api-Department-Model">Department</a> that has been deleted
 *
 */

/**
 * @api {put} /departments/:id Put Department
 * @apiVersion 0.0.1
 * @apiName Put
 * @apiGroup Department
 * @apiUse Put
 *
 * @apiuse JwtHeader
 *
 * @apiParam (Query) {String} id MongoID
 *
 * @apiUse Response
 * @apiSuccess {Department} data <a href="#api-Department-Model">Department</a> that has been 'put'
 *
 */

/**
 * @api {patch} /departments/:id Patch Department
 * @apiVersion 0.0.1
 * @apiName Patch
 * @apiGroup Department
 * @apiUse Patch
 *
 * @apiuse JwtHeader
 *
 * @apiParam (Query) {String} id MongoID
 *
 * @apiUse Response
 * @apiSuccess {Department} data <a href="#api-Department-Model">Department</a> that has been patched
 *
 */

/**
 * @api {get} /departments/:id Get Department
 * @apiVersion 0.0.1
 * @apiName Getone
 * @apiGroup Department
 *
 * @apiUse GetOne
 * @apiUse JwtHeader
 *
 * @apiParam (Query) {String} id MongoID
 *
 * @apiUse Response
 * @apiSuccess {Department} data <a href="#api-Department-Model">Department</a> that has been patched
 *
 */
