/**
 * @api {none} / Model Structure
 * @apiVersion 0.0.1
 * @apiName Model
 * @apiGroup Route
 *
 * @apiDeprecated This is only used to define the model.
 *
 * @apiSuccess (Model Autogenerated) {String} _id MongoID this is autogenerated depending on the HTTP method
 * @apiSuccess (Model Autogenerated) {String} updated_at Indicated when the document has been updated
 * @apiSuccess (Model Autogenerated) {String} created_at Indicated when the document has been created
 * @apiSuccess (Model) {String} name
 * @apiSuccess (Model) {User} [walked_by] The <a href="#api-User-Model">User</a> that walked this route
 * @apiSuccess (Model) {Date} [start_time]
 * @apiSuccess (Model) {Date} [end_time]
 * @apiSuccess (Model) {Object[]} waypoints
 * @apiSuccess (Model) {string} .type <b>Default: </b> "LineString"
 * @apiSuccess (Model) {Double[]} .coordinates containing long and lang double
 * @apiSuccess (Model) {obstacles[]} [obstacles] Array of <a href="#api-Obstacle-Model">Obstacle</a>s
 */

/**
 * @api {get} /routes Get Routes
 * @apiVersion 0.0.1
 * @apiName Get
 * @apiGroup Route
 *
 * @apiuse JwtHeader
 *
 * @apiUse Response
 * @apiSuccess {Route[]} data Array of <a href="#api-Route-Model">Route</a>s
 *
 */

/**
 * @api {get} /routes/:id Get Route
 * @apiVersion 0.0.1
 * @apiName GetOne
 * @apiGroup Route
 *
 * @apiUse GetOne
 * @apiuse JwtHeader
 *
 * @apiParam (Query) {String} id MongoID
 *
 * @apiUse Response
 * @apiSuccess {Route} data of <a href="#api-Route-Model">Route</a> for the specified id
 *
 */

/**
 * @api {post} /routes Post Route
 * @apiVersion 0.0.1
 * @apiName Post
 * @apiGroup Route
 *
 * @apiuse JwtHeader
 *
 * @apiUse Response
 * @apiSuccess {Route} data <a href="#api-Route-Model">Route</a> that has been posted
 *
 */

/**
 * @api {delete} /routes/:id Delete Route
 * @apiVersion 0.0.1
 * @apiName Delete
 * @apiGroup Route
 *
 * @apiuse JwtHeader
 *
 * @apiParam (Query) {String} id MongoID
 *
 * @apiUse Response
 * @apiSuccess {Route} data <a href="#api-Route-Model">Route</a> that has been deleted
 *
 */

/**
 * @api {put} /routes/:id Put Route
 * @apiVersion 0.0.1
 * @apiName Put
 * @apiGroup Route
 * @apiUse Put
 *
 * @apiuse JwtHeader
 *
 * @apiParam (Query) {String} id MongoID
 *
 * @apiUse Response
 * @apiSuccess {Route} data <a href="#api-Route-Model">Route</a> that has been 'put'
 *
 */

/**
 * @api {patch} /routes/:id Patch Route
 * @apiVersion 0.0.1
 * @apiName Patch
 * @apiGroup Route
 * @apiUse Patch
 *
 * @apiuse JwtHeader
 *
 * @apiParam (Query) {String} id MongoID
 *
 * @apiUse Response
 * @apiSuccess {Route} data <a href="#api-Route-Model">Route</a> that has been patched
 *
 */
